services:
  mysql:
    # Use the official MySQL image.
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT:-25060}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-devdogs}
    # Ensure that the database is healthy before allowing dependent services to start.
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Restart the container if it crashes.
    restart: on-failure:3
  s3:
    image: localstack/localstack:s3-latest
    ports:
      - "${S3_PORT:-4566}:4566"
    environment:
      - AWS_REGION=${S3_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY:-test}
    restart: on-failure:3