name: CI
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  TURBO_TEAM: ${{ secrets.VERCEL_TEAM_ID }}
on:
  pull_request:
    branches-ignore: 
      - "main"
  
jobs:
  Checkstyle-Lint-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Lint and Format
        run: pnpm check
      - name: Pull Vercel Environment Information
        run: 
          - pnpm vercel pull --yes --environment=preview --git-branch=${{ github.base_ref }} --token=${{ secrets.VERCEL_TOKEN }}
          - pnpm vercel env pull --environment=development .env
      - name: Build Project Artifacts
        run: pnpm vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Setup Docker
        run: pnpm docker:ready
      - name: Clone remote database
        run: pnpm dotenv -e .env.local -- bash -c 'mysqldump --single-transaction -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE | mysql -h 127.0.0.1 -P 25060 -u root -p'password' devdogs'
      - name: Validate Migration
        run: pnpm db:migrate